[package]
name = "griphd"
version = "0.1.0"
edition = "2024"

[dependencies]

crc32fast = "1.4.2"
reqwest = { version = "0.12.22", features = ["blocking", "json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
